//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 抓取信息.GrabNews {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GrabNews.GrabNewsSoap")]
    public interface GrabNewsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/News", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string News(System.Data.DataTable dt);
        
        // CODEGEN: 参数“imgBytesIn”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TOImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        抓取信息.GrabNews.TOImageResponse TOImage(抓取信息.GrabNews.TOImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TOImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TOImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imgBytesIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string filename;
        
        public TOImageRequest() {
        }
        
        public TOImageRequest(byte[] imgBytesIn, string filename) {
            this.imgBytesIn = imgBytesIn;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TOImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TOImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TOImageResult;
        
        public TOImageResponse() {
        }
        
        public TOImageResponse(string TOImageResult) {
            this.TOImageResult = TOImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GrabNewsSoapChannel : 抓取信息.GrabNews.GrabNewsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrabNewsSoapClient : System.ServiceModel.ClientBase<抓取信息.GrabNews.GrabNewsSoap>, 抓取信息.GrabNews.GrabNewsSoap {
        
        public GrabNewsSoapClient() {
        }
        
        public GrabNewsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrabNewsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrabNewsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrabNewsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string News(System.Data.DataTable dt) {
            return base.Channel.News(dt);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        抓取信息.GrabNews.TOImageResponse 抓取信息.GrabNews.GrabNewsSoap.TOImage(抓取信息.GrabNews.TOImageRequest request) {
            return base.Channel.TOImage(request);
        }
        
        public string TOImage(byte[] imgBytesIn, string filename) {
            抓取信息.GrabNews.TOImageRequest inValue = new 抓取信息.GrabNews.TOImageRequest();
            inValue.imgBytesIn = imgBytesIn;
            inValue.filename = filename;
            抓取信息.GrabNews.TOImageResponse retVal = ((抓取信息.GrabNews.GrabNewsSoap)(this)).TOImage(inValue);
            return retVal.TOImageResult;
        }
    }
}
